name: relead
description: Free WiFi, Everywhere, for Everyone!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
  regexpattern: ^2.1.0
  email_validator: ^2.1.17
  pinput: ^2.2.16
  equatable: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  latlong2: ^0.8.1
  material_floating_search_bar: ^0.3.7
  anim_search_bar: ^2.0.2
  syncfusion_flutter_maps: ^20.3.60
  flutter_locales: ^2.0.2
  localization: ^2.1.0
  easy_localization: ^3.0.1
  localstorage: ^4.0.0+1
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  flutter_profile_picture: ^2.0.0
  app_settings: ^4.1.8
  after_layout: ^1.2.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  connectivity_plus: ^3.0.2
  animated_snack_bar: ^0.3.0
  device_preview: ^1.1.0
  shared_preferences_web: ^2.0.4
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.5
  fluttertoast: ^8.1.2
  image_picker: ^0.8.6+1
  modal_progress_hud_nsn: ^0.3.0
  responsive_framework: ^0.2.0
  photo_view: ^0.14.0
  flutter_map_tile_caching: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logoRelead.jpg
    - assets/images/AbdallahRaies.jpg
    - assets/images/loop.png
    - assets/images/Mail.png
    - assets/images/OopsFace.png
    - assets/images/Registration.png
    - assets/images/Reset_password.png
    - assets/images/welcome_page.png
    - assets/images/OopsFace.png
    - assets/images/half_circle.png
    - assets/images/phoneRelead.png
    - assets/icons/pin.png
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/icon-Relead.png
    - assets/images/bubbles.svg
    - assets/icons/moon.svg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon-launcher.png"
